# Generated by Django 5.0.1 on 2024-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('linkedin', models.URLField(verbose_name='LinkedIN')),
                ('youtube', models.URLField(verbose_name='Youtube')),
                ('whatsapp', models.URLField(verbose_name='Whatsapp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
