# Generated by Django 4.2.10 on 2024-02-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaurls',
            options={'verbose_name_plural': 'Social Media URLS'},
        ),
    ]
