# Generated by Django 5.0.1 on 2024-02-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_title_category_name_price_color_price_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='slug',
        ),
    ]
