# Generated by Django 5.0.1 on 2024-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_category_is_deleted_remove_color_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Color Slug'),
        ),
    ]
