# Generated by Django 5.0.1 on 2024-02-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_product_currency_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency_ids',
        ),
    ]
