# Generated by Django 5.0.1 on 2024-02-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_choice',
        ),
    ]
