# Generated by Django 5.0.1 on 2024-02-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_rename_color_color_color_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name=' Name'),
            preserve_default=False,
        ),
    ]
