# Generated by Django 5.0.1 on 2024-02-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catalog_delete_common_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Catalog Model'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': ' Model'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': ' Model'},
        ),
    ]
