# Generated by Django 5.0.1 on 2024-02-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_color_category_alter_color_color_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Size Model'},
        ),
    ]
